# Generated by Django 4.2.7 on 2024-10-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_assigned_to_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='available', max_length=10),
        ),
    ]
